/*
    MovieTicketKioskUserRequirements file
    A file that is created to store ticket kiosk operation instances with variables of ticketCount, popcornCount, drinkCount, username, usedSeats (a HashMap used to record the used seats so that there would be no duplicated seats sold), and movieTitle that is added into it; bookingCode, usernameInitials, seat, and memberDiscount that is generated by the program from input (setter methods) or from random numbers; and constants of ticketPrice, popcornPrice, drinkPrice, and salesTaxPercentage used by different operations in order to return the final formatted ticket via the toString method
    Completed challenge one (no duplicated seats+infinite printing)
    Richard Jiang
    2026/9/9
 */
import java.util.HashMap;
public class MovieTicketKioskUserRequirements {
    private int ticketCount;
    private int popcornCount;
    private int drinkCount;
    private String username;
    private String movieTitle;
    private String bookingCode;
    private int[] seat=new int[2];//index 0 denoting row while index 1 denotes seat number
    public String usernameInitials;
    private final double ticketPrice=12.50;
    private final double popcornPrice=6.75;
    private final double drinkPrice=4.25;
    private final double salesTaxPercentage=8.25;
    private int memberDiscount;
    private HashMap<String, Integer> usedSeats;
    public void setTicketCount(int ticketCount){
        this.ticketCount=ticketCount;
        if (ticketCount<=0){
            this.ticketCount=0;
        }
    }
    public void setPopcornCount(int popcornCount){
        this.popcornCount=popcornCount;
        if (popcornCount<=0){
            this.popcornCount=0;
        }
    }
    public void setDrinkCount(int drinkCount){
        this.drinkCount=drinkCount;
        if (drinkCount<=0){
            this.drinkCount=0;
        }
    }
    public void setUsername(String username){
        this.username=username;
        usernameInitials=(username.substring(0, 1)+username.substring(username.indexOf(" ")+1, username.indexOf(" ")+2)).toUpperCase();
    }
    public void setMovieTitle(String movieTitle){
        this.movieTitle=movieTitle;
    }
    public void generateBookingCodeAndSeatingAndMemberDiscount(){
        int randomUserCode=(int)(Math.random()*900)+100;
        if (movieTitle.length()<=3){
            bookingCode=movieTitle.toUpperCase()+"-"+randomUserCode;
        }
        else{
            bookingCode=movieTitle.substring(0, 3).toUpperCase()+"-"+randomUserCode;
        }
        seat[0]=(int)(Math.random()*10+1);
        seat[1]=(int)(Math.random()*20+1);
        //seat[0]=1;
        //seat[1]=1;
        while (usedSeats.getOrDefault(seat[0]+","+seat[1], 0)==1){
            seat[0]=(int)(Math.random()*10+1);
            seat[1]=(int)(Math.random()*20+1);
        }
        memberDiscount=(int)(Math.random()*11)+5;
    }
    public int[] getSeat(){
        return seat;
    }
    public MovieTicketKioskUserRequirements(HashMap<String, Integer> usedSeats){
        this.usedSeats=usedSeats;
    }
    //String.format() reference from https://www.w3schools.com/java/ref_string_format.asp only used in order to ensure the strict requirement of two decimal places
    public String toString(){
        String finalReturnString="\n====================================================\nSTARLIGHT CINEMA MOVIE TICKET\n====================================================\n";
        finalReturnString+="Booking Code: "+bookingCode;
        finalReturnString+="\nCustomer: "+username+" ("+usernameInitials+")";
        finalReturnString+="\nMovie: "+movieTitle;
        finalReturnString+="\nSeat: Row "+seat[0]+" Seat "+seat[1]+"";
        finalReturnString+="\n====================================================\n";
        finalReturnString+="ITEM\tQTY\tPRICE\tTOTAL";
        double ticketTotalPrice=ticketPrice*ticketCount;
        double popcornTotalPrice=popcornCount*popcornPrice;
        double drinkTotalPrice=drinkCount*drinkPrice;
        finalReturnString+="\nTicket\t"+ticketCount+"\t$"+String.format("%.2f", ticketPrice)+"\t$"+String.format("%.2f", ticketTotalPrice);
        finalReturnString+="\nPopcorn\t"+popcornCount+"\t$"+popcornPrice+"\t$"+String.format("%.2f", popcornTotalPrice);
        finalReturnString+="\nDrink\t"+drinkCount+"\t$"+drinkPrice+"\t$"+String.format("%.2f", drinkTotalPrice);
        double totalValue=ticketTotalPrice+popcornTotalPrice+drinkTotalPrice;
        finalReturnString+="\n----------------------------------------------------";
        finalReturnString+="\nSubtotal\t$"+String.format("%.2f", totalValue);
        double memberDiscountValue=totalValue*memberDiscount/100.0;
        finalReturnString+="\nMember Discount ("+memberDiscount+"%)\t-$"+String.format("%.2f", memberDiscountValue);
        totalValue-=memberDiscountValue;
        double salesTaxValue=totalValue*salesTaxPercentage/100.0;
        finalReturnString+="\nTax ("+salesTaxPercentage+"%)\t$"+String.format("%.2f", salesTaxValue);
        totalValue+=salesTaxValue;
        totalValue=(totalValue*1000)/1000.0;
        finalReturnString+="\nTOTAL\t$"+String.format("%.2f", totalValue);
        finalReturnString+="\n====================================================";
        finalReturnString+="\nThank you, "+usernameInitials+" - enjoy "+movieTitle+"!";
        finalReturnString+="\n====================================================";
        return finalReturnString;
    }
}